### ISSUE TITLE
crul fails parsing header

### ISSUE THREAD

**Issue by KevCaz** [VLucet/rgovcan#11]
Currently, we cannot load the package: 

```R
R> devtools::load_all()                                          
Loading ckanr
Error in xx[[2]] : subscript out of bounds
```

This is due to a bug in crul (see https://github.com/ropensci/crul/issues/150). We should wait and see!

**Comment by VLucet** [comment]
@KevCaz I am still getting the error even after installing the latest github version of `crul`. Am I doing something wrong or are you still getting the issue as well?

**Comment by KevCaz** [comment]
It's working here, we'll have to deal with warnings though...

**Comment by VLucet** [comment]
It's working for me as well - my tired monday evening brain mistakened the warnings for errors. We do need to deal with those. Any suggestions?

**Comment by KevCaz** [comment]
yep, we'll have to use `suppressWarnings()` cause otherwise we won't be able to test the package.... I'm working on a PR now.

**Comment by KevCaz** [comment]
sckott has suggested https://github.com/ropensci/conditionz, worth considering.

**Comment by VLucet** [comment]
This looks like a very useful package. Since your comment (and advice!) on the last PR, I would be warry of adding new dependencies unless it is really necessary. Let's stick to `suppressWarnings()`, if you agree.

**Comment by KevCaz** [comment]
Yep, let's do that for the time being!
